mozilla/dispensary

- src/dispensary.js
- src/utils.js
- tests/test.utils.js
Just a quick bit of housekeeping before I add the match API.
> Tidy up urlFormat and add tests

- package.json
> chore(package): update babel-core to version 6.4.5

- src/dispensary.js
- src/main.js
- tests/test.dispensary.js
- tests/test.hasher.js
This should allow us to integrate this into Add-ons Linter and close https://github.com/mozilla/addons-linter/issues/66
> Add match API

- package.json
> chore: update sinon

- tests/test.dispensary.js
Very simple additional, until #5 is implemented.
> Make timeouts for network tests longer

- .babelrc
- bin/dispensary
- package.json
- src/cli.js
- src/dispensary.js
- tests/test.dispensary.js
Fixes a few bugs that crept up while adding more tests.
> Improve test coverage

- package.json
> Set en-US locale for running tests

- src/versions.js
- tests/test.versions.js
> Don't include alpha, beta, and rc libraries

- package.json
- src/dispensary.js
- tests/test.dispensary.js
> Sort hashes

- src/dispensary.js
- tests/test.dispensary.js
This fixes wrongful downloads like 
```
https://raw.githubusercontent.com/moment/moment/1.6.0/min/moment.js produced code 404
```
> Use correct file to fetch

- src/main.js
Addresses https://github.com/mozilla/addons-linter/issues/735
> Don't check for command line config unless run via CLI

- package.json
Closes #303
https://greenkeeper.io/
> fix(package): update eslint to version 3.14.1

- package.json
Closes #304
https://greenkeeper.io/
> fix(package): update source-map-support to version 0.4.11

- package.json
This reverts commit 94785bfa30fc141f8fd7ba4b147555ca92f6be15.
> Revert "chore(package): update grunt-webpack to version 3.0.0"

- package.json
https://nodesecurity.io/advisories/request_remote-memory-exposure
> Update 'requests' dependency

- package.json
> chore(package): update sinon to version 2.3.2

- package.json
> fix(package): update source-map-support to version 0.4.18

- package.json
> chore(package): update babel-eslint to version 8.0.0

- package.json
> fix(package): update yargs to version 9.0.1

- package.json
> fix(package): update yargs to version 10.0.3

- package.json
> fix(package): update source-map-support to version 0.5.3

- package.json
> fix(package): update yargs to version 11.0.0

- package.json
> chore(package): update grunt-webpack to version 3.1.1

- package.json
> fix(package): update pino to version 4.16.1

- package.json
> fix(package): update pino to version 5.0.3

- package.json
> fix(package): update pino to version 5.2.0

- package.json
> fix(package): update pino to version 5.4.0

- package.json
> move snyk to devDependencies

- .npmignore
- CONTRIBUTING.md
- src/cli.js
- src/dispensary.js
- tests/dispensary.test.js
> Clean-up jscs leftovers
